export { default as Header } from "./Header"
export { default as Game } from "./Game"
export { default as GuessCircle } from "./GuessCircle"
export { default as PastGuesses } from "./PastGuesses"
export { default as Footer } from "./Footer"